// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Page");

function change($$event) {
  return /* Change */[$$event.target.value];
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("section", undefined, self[/* state */2], React.createElement("div", undefined, React.createElement("input", {
                          type: "text",
                          onChange: Curry._1(self[/* reduce */1], change)
                        })));
    });
  newrecord[/* initialState */10] = (function () {
      return "";
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [action[0]]);
    });
  return newrecord;
}

exports.component = component;
exports.change    = change;
exports.make      = make;
/* component Not a pure module */
